### ISSUE TITLE
Cannot read properties 'activities' of undefined

### ISSUE THREAD

**Issue by alechp** [pauloelias/gatsby-tailwind-emotion-starter#4]
## Error
> This is what I see immediately after running `npm install` and `npm run develop`

![Screen Shot 2020-06-03 at 6 12 47 PM](https://user-images.githubusercontent.com/3058939/83704470-076ed380-a5c7-11ea-9a95-ef2bf9577c6d.png)

## Problem
Outdated version of Gatsby

## Solution
Update gatsby

![Screen Shot 2020-06-03 at 6 13 10 PM](https://user-images.githubusercontent.com/3058939/83704540-308f6400-a5c7-11ea-88f0-68df34b0b71c.png)

I tested these versions:
* 2.20.24
* 2.22.20

This dependency update would go nicely with this PR: https://github.com/pauloelias/gatsby-tailwind-emotion-starter/pull/3

**Comment by pauloelias** [comment]
@alechp thanks for the report!

I'll get this updated soon.

**Comment by pauloelias** [comment]
Fixed in latest release.
